security:
    encoders:
     # use your user class name here
        App\Entity\Utilisateurs:
            # Use native password encoder
            # This value auto-selects the best possible hashing algorithm
            # (i.e. Sodium when available).
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        # users_in_database:
        #     entity:
        #         class: App\Entity\Utilisateurs
        #         property: email_utilisateur
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Utilisateurs
                property: email_utilisateur
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            # provider: users_in_memory
            # provider: users_in_database
            provider: app_user_provider


            # form_login: 
            #     login_path: compte_connexion
            #     check_path: compte_connexion
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

                # csrf_token_generator: security.csrf.token_manager
                # csrf_parameter: _csrf_security_token
                # csrf_token_id: a_private_string
                # default_target_path: home

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
